StudentsPerformanceAnalysis3/StudentsPerformanceAnalysis3/urls.py
from django.contrib import admin
from django.urls import path, include
from classroom.views import classroom, students, teachers
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentsPerformanceAnalysis3/classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers, charts
urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('studentdetail/<int:pk>', students.StudentsDetailView.as_view(), name='student_detail'),
        path('student/<int:pk>', students.StudentUpdateView.as_view(), name='student_update'),
        path('editsubjects/<int:pk>', students.EditSubjectsView.as_view(), name='edit_subjects'),
        path('viewSubjects', students.SubjectsView.as_view(), name='view_subjects'),
        path('recordResult/<int:pk>', students.RecordTestResult.as_view(), name='record_test_result'),
        path('editTestResult/<int:pk>', students.TestResultEditView.as_view(), name='edit_test_result'),
        path('delete/<int:pk>', students.TestResultDelete.as_view(), name='delete'),
        path('guardianUpdate/<int:pk>', students.GuardianUpdateView.as_view(), name='guardian_update'),
        path('otherDetails/<int:pk>', students.OtherDetailsUpdateView.as_view(), name='other_details_update'),
        path('personalityTest', students.PersonalityTest.as_view(), name='personality_test'),
        path('updatePersonality/<int:pk>', students.PersonalityTest2.as_view(),  name='update_personality'),
        path('updatePersonality3/<int:pk>', students.PersonalityTest3.as_view(),  name='update_personality3'),
        path('updatePersonality4/<int:pk>', students.PersonalityTest4.as_view(),  name='update_personality4'),
        path('careers', students.CareerListView.as_view(), name='career_list_view'),
        path('bar_graph/<int:sub_pk>/<int:student_pk>', students.BarGraph.as_view(), name='bar_graphs'),
        path('second_careers', students.SecondCareers.as_view(), name='second_careers')
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.TeacherDashboard.as_view(), name='teacher_dashboard'),
        path('attendanceRegister/<int:pk>', teachers.Attendance.as_view(), name='attendance'),
        path('setAttendanceStatus/<int:pk>', teachers.Attendance.set_attendance_status, name='set_attendance_status'),
        path('setAbsent/<int:pk>', teachers.Attendance.set_absent, name='set_absent'),
        path('saveAttendanceRecord/<int:pk>', teachers.Attendance.save_records, name='save_records'),
        path('attendanceDay', teachers.AttendanceDays.as_view(), name='attendance_days'),
        path('subjects', teachers.Subjects.as_view(), name='teacher_subjects'),
        path('subject_test/<int:pk>', teachers.SubjectsTestsView.as_view(), name='subject_tests')

    ], 'classroom'), namespace='teachers')),
]

StudentsPerformanceAnalysis3/classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from datetime import date
from django.urls import reverse

# Create your models here.

Gender_Choices = (('Male', 'Male'), ('Female', 'Female'))
Guardian = (('Father', 'Father'),
                ('Mother', 'Mother'),
                ('Other', 'Other'))
YES_OR_NO = (('Yes', 'Yes'), ('No', 'No'))
Education_level = (('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'))
Argument = (('Thinking', 'argue your point completely as long as it is factual'),
            ('Feeling', 'give in if your counter part becomes sensitive'))
making_a_decision = (('Thinking', 'assess the situation, outline the pros and cons, then decide'),
                     ('Feeling', 'listen to your feelings , always follow your heart'))
word_description = (('Thinking', 'logical'),  ('Feeling', 'emotional'))
facts = (('Thinking', 'sticking to facts'), ('Feeling', 'understanding why something happened'))
relating = (('Thinking', 'True'), ('Feeling', 'False'))
queue = (('Introvert', 'stay glued to my phone'),
         ('Extrovert', 'chat to the person next to me'))
class_projects = (('Extrovert', 'when you are part of a group'),
                  ('Introvert', 'when you can work by yourself'))
description = (('Extrovert', 'enjoy having a circle of acquaintances'),
               ('Introvert', 'relatively reserved and quiet'))
friends = (('Extrovert', 'You become friends on the spot'),
           ('Introvert', 'It will take a few more conversations before you open up'))
roommates = (('Introvert', 'You would much rather live by yourself'),
             ('Extrovert', 'It is great to have someone there when you get home'))
mathematical = (('Judging', 'stick to the methods taught by your teacher'),
                ('Perceiving', 'explore different methods for discovery'))
yes_or_no = (('Judging', 'Yes'), ('Perceiving', 'No'))
trip = (('Judging', 'Inquire thoroughly about the trip details for planning purposes. It is better to be fully armed'),
        ('Perceiving', 'Just get in the school bus and go , the best things happen spontaneously'))
appointments = (('Judging', 'Yes'), ('Perceiving', 'No'))
order = (('Judging', 'super organised'),
         ('Perceiving', 'a jumble of things you are working on'))
info_description = (('Sensing', 'the most important thing for me is what is happening here and now. '
                                'I assess real situations and pay attention to detail'),
                    ('Intuition', 'facts are boring. I love to dream and play over upcoming events in my mind'))
yes_no = (('Sensing', 'No'), ('Intuition', 'Yes'))
situation = (('Sensing', 'pay more attention to the current situation'),
             ('Intuition', 'think of  possible sequence of events'))
imagination = (('Sensing', 'No'), ('Intuition', 'Yes'))
knowledge = (('Intuition', 'Books and manuals'), ('Sensing', 'hands on experience'))
subject_category = (('Commercials', 'Commercials'), ('Arts', 'Arts'), ('Sciences', 'Sciences'))


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Test(models.Model):
    test_title = models.CharField(max_length=45, default='')
    total_score = models.IntegerField(default=100)
    subject = models.ForeignKey('Subject', on_delete=models.PROTECT, blank=True, null=True)
    test_number = models.IntegerField(default=1)

    def __str__(self):
        return self.test_title


class SubjectAverage(models.Model):
    subject_average_mark = models.IntegerField(default=0)
    subject = models.ForeignKey('Subject', on_delete=models.PROTECT)
    student = models.ForeignKey('Student', on_delete=models.PROTECT)

    def __str__(self):
        return self.student.first_name + " " + self.subject.subject_title


class CategoryAverage(models.Model):
    category_average_mark = models.IntegerField(default=0)
    category_name = models.CharField(choices=subject_category, max_length=20, default='')
    student = models.ForeignKey('Student', on_delete=models.PROTECT)

    def __str__(self):
        return self.student.first_name + "Category Average"


class TestResult(models.Model):
    test_score = models.IntegerField(default=0)
    test = models.ForeignKey(Test, on_delete=models.PROTECT, blank=True, null=True)
    student = models.ForeignKey('Student', on_delete=models.PROTECT, blank=True, null=True)
    pass_status = models.CharField(max_length=10, default='')
    percentage = models.FloatField(max_length=10, default=0.0)

    def __str__(self):
        return self.test.test_title


class Personality(models.Model):
    identifier = models.IntegerField(default='')
    personality_name = models.CharField(max_length=10, default='')
    image = models.ImageField(upload_to='personality_image', blank=True)
    energy_title = models.CharField(max_length=15, default='')
    energy_description1 = models.CharField(max_length=50, default='')
    energy_description2 = models.CharField(max_length=50, default='')
    energy_description3 = models.CharField(max_length=50, default='')
    energy_description4 = models.CharField(max_length=50, default='')
    energy_description5 = models.CharField(max_length=50, default='')
    information_title = models.CharField(max_length=15, default='')
    information_description1 = models.CharField(max_length=50, default='')
    information_description2 = models.CharField(max_length=50, default='')
    information_description3 = models.CharField(max_length=50, default='')
    information_description4 = models.CharField(max_length=50, default='')
    information_description5 = models.CharField(max_length=50, default='')
    decision_title = models.CharField(max_length=15, default='')
    decision_description1 = models.CharField(max_length=50, default='')
    decision_description2 = models.CharField(max_length=50, default='')
    decision_description3 = models.CharField(max_length=50, default='')
    decision_description4 = models.CharField(max_length=50, default='')
    decision_description5 = models.CharField(max_length=50, default='')
    life_title = models.CharField(max_length=15, default='')
    life_description1 = models.CharField(max_length=50, default='')
    life_description2 = models.CharField(max_length=50, default='')
    life_description3 = models.CharField(max_length=50, default='')
    life_description4 = models.CharField(max_length=50, default='')
    life_description5 = models.CharField(max_length=50, default='')
    energy_explanation = models.CharField(max_length=500, default='')
    information_explanation = models.CharField(max_length=500, default='')
    decision_explanation = models.CharField(max_length=500, default='')
    life_explanation = models.CharField(max_length=500, default='', blank=True)
    teaching_method1 = models.CharField(max_length=1000, default='', blank=True)
    teaching_method2 = models.CharField(max_length=1000, default='', blank=True)
    teaching_method3 = models.CharField(max_length=1000, default='', blank=True)
    teaching_method4 = models.CharField(max_length=1000, default='', blank=True)
    teaching_method5 = models.CharField(max_length=1000, default='', blank=True)
    teaching_method6 = models.CharField(max_length=1000, default='', blank=True)

    def __str__(self):
        return self.personality_name


class Subject(models.Model):
        subject_title = models.CharField(max_length=30)
        number_of_tests = models.IntegerField(default=1)
        category = models.CharField(max_length=15, choices=subject_category, blank=True, default='')

        def __str__(self):
            return self.subject_title


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=45, default='')
    last_name = models.CharField(max_length=45, default='')
    email = models.CharField(max_length=100, default='')
    phone_number = models.CharField(max_length=20, default='')
    class_name = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.last_name


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=45, default='')
    second_name = models.CharField(max_length=45, default='')
    last_name = models.CharField(max_length=45, default='', blank=True)
    age = models.IntegerField(default=1, blank=True)
    gender = models.CharField(max_length=10, choices=Gender_Choices, default='', blank=True)
    date_of_birth = models.DateField("Date", default=date.today, blank=True)
    guardian = models.CharField(max_length=10, choices=Guardian, default='', blank=True)
    guardian_first_name = models.CharField(max_length=20, default='', blank=True)
    guardian_last_name = models.CharField(max_length=20, default='', blank=True)
    guardian_phone_number = models.CharField(max_length=20, default='')
    guardian_email = models.EmailField(max_length=100, default='', blank=True)
    extra_paid_classes = models.CharField(max_length=3, choices=YES_OR_NO, default='')
    internet_access = models.CharField(max_length=3, choices=YES_OR_NO, default='')
    intend_to_pursue = models.CharField(max_length=3, choices=YES_OR_NO, default='')
    out_going = models.CharField(max_length=3, choices=YES_OR_NO, default='')
    free_time_after_school = models.IntegerField(default=1)
    average_weekly_study_time = models.IntegerField(default=1)
    family_size = models.IntegerField(default=1)
    email = models.CharField(max_length=100, default='')
    subjects = models.ManyToManyField(Subject)
    guardian_education_level = models.CharField(max_length=10, choices=Education_level, default='')
    personality = models.ForeignKey(Personality, on_delete=models.PROTECT, default='', blank=True, null=True)

StudentsPerformanceAnalysis3/classroom/views/charts.py
import pygal

from ..models import Fruit


class FruitPieChart():

    def __init__(self, student, **kwargs, ):
        self.chart = pygal.Pie(**kwargs)
        self.chart.title = 'Personality details'
        self.student = student

    def get_data(self):
        '''
        Query the db for chart data, pack them into a dict and return it.
        '''
        data = {self.student.personality.energy_title: 90, self.student.personality.information_title: 20,
                self.student.personality.decision_title: 70, self.student.personality.life_title: 30}

        return data

    def generate(self):
        # Get chart data
        chart_data = self.get_data()

        # Add data to chart
        for key, value in chart_data.items():
            self.chart.add(key, value)

        # Return the rendered SVG
        return self.chart.render(is_unicode=True)

StudentsPerformanceAnalysis3/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from classroom.models import Student

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:teacher_dashboard')
        else:
            return redirect('students:student_detail', pk=request.user.pk,)
    return render(request, 'classroom/home.html')

StudentsPerformanceAnalysis3/templates/classroom/teachers/attendance_days.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<ul class="list-group">
{% for day in days %}
    <a href="{% url 'classroom:attendance' pk=day.pk %}">
    {% if day.checked == True %}
  <li class="list-group-item justify-content-center"><button class="btn btn-block btn-student" disabled><b>{{ day.day_title }}</b></button></li>
    {% else %}
  <li class="list-group-item justify-content-center"><button class="btn btn-block btn-student" ><b>{{ day.day_title }}</b></button></li>
    {% endif %}
    </a>
{% endfor %}
</ul>
{% endblock %}

StudentsPerformanceAnalysis3/templates/classroom/teachers/attendance_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
     <table class="table table-striped table-bordered" id="studentList" style="width:100%">
              <thead>
              <tr><td><b>First Name</b></td><td><b>Middle Name</b></td><td><b>Last Name</b></td><td></td><td></td><td></td></tr>
              </thead>
              <tbody>
                 {% for attendance_record in attendance_records_list %}
                  <tr>
                      <td>{{ attendance_record.student.first_name }}</td>
                      <td>{{ attendance_record.student.second_name }}</td>
                      <td>{{ attendance_record.student.last_name }}</td>
                      <td>{{ attendance_record.day.day_title }}</td>
                     <td> <form method="get" action="{% url "classroom:set_attendance_status" pk=attendance_record.pk%}" id="presentForm">
                         {% csrf_token %}
                          <input type="submit" class="btn btn-success" value="Present" name="present_btn">
                     </form></td>
                       <td> <form method="get" action="{% url "classroom:set_absent" pk=attendance_record.pk%}" id="absentForm">
                         {% csrf_token %}
                          <input type="submit" class="btn btn-danger" value="Absent" name="absent_btn">
                     </form></td>
                   </tr>
                 {% endfor %}

              </tbody>
          <tfoot></tfoot>
          </table>
    <br>
     <td> <form method="get" action="{% url "classroom:save_records" pk=day.pk%}" id="saveForm">
          {% csrf_token %}
          <input type="submit" class="btn btn-student btn-block" value="Save" name="save_btn">
         </form>
     </td>
    <script type="text/javascript">
      $(document).on('submit', '#presentForm', function (e) {
          e.preventDefault();

          $.ajax({
              type:'POST',
              url:$(this).attr('action'),
              success: function () {
               alert('Student Present')

              },
              data:''
          },)
      });

      $(document).on('submit', '#absentForm', function (e) {
          e.preventDefault();

          $.ajax({
              type:'POST',
              url:$(this).attr('action'),
              success: function () {
               alert('Student Absent')

              },
              data:''
          },)
      });
       $(document).on('submit', '#saveForm', function (e) {

          $.ajax({
              type:'POST',
              url:$(this).attr('action'),
              success: function () {
               alert('Attendance Record saved')

              },
              data:''
          },)
      });


    </script>
{% endblock %}

StudentsPerformanceAnalysis3/templates/classroom/teachers/attendanceexample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 ATTENDANCE!!!!!
</body>
</html>

StudentsPerformanceAnalysis3/templates/classroom/teachers/student_performance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

StudentsPerformanceAnalysis3/templates/classroom/teachers/students_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

StudentsPerformanceAnalysis3/templates/classroom/teachers/subject_test_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<ul class="list-group">
{% for test in tests %}
    <div class="panel panel-default">
    <div class="panel-heading">    <span class="badge badge-pill badge-primary"><b>{{ test.test_title }}</b></span></div>
    <div class="panel-body">
     <table class="table table-striped">
    <thead>
    <tr>
        <td><b>First Name</b></td>
        <td><b>Last Name</b></td>
        <td><b>Test Score</b></td>
    </tr>
    </thead>
    <tbody>
    {% for testresult in test.testresult_set.all %}
        <tr>
       <td>{{ testresult.student.first_name}}</td>
       <td>{{ testresult.student.last_name }}</td>
        <td>{{ testresult.test_score}}</td>
       </tr>
       {% endfor %}
    </tbody>
    <tfoot>

    </tfoot>
    </table>
    </div>
    </div>


{% endfor %}
</ul>
{% endblock %}

StudentsPerformanceAnalysis3/templates/classroom/teachers/teacher_dashboard.html
{% load staticfiles %}
<html lang="en">
<head>
  <title>Blaze</title>
   <link rel="icon" href="{% static 'img/favicon.png' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'jquery-3.3.1.js' %}"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 550px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* On small screens, set height to 'auto' for the grid */
    @media screen and (max-width: 767px) {
      .row.content {height: auto;}
    }
    .well{
    background: darkblue;
    color: white;
}
 #student {
  background: #8980a5;
 }
 #attendance{
     background: #8980a5;
 }
 #subjects{
     background: #8980a5;
 }
 #graphs{
     background: #8980a5 ;
 }
  #studentList{
      width: 100%;
  }
  </style>
    <script type="javascript">
   $('#studentList').dataTable();
    </script>
</head>
<body>
 <div class="col-6 text-right">
     {% if user.is_authenticated %}
     <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
     {% else %}
     <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
     <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
     {% endif %}
 </div>
<nav class="navbar navbar-inverse visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row content">
      <div class="col-sm-1">
      </div>
      <div class="col-sm-9">
      <div class="row">
          <div class="col-sm-3">
          <div class="well " id="student">
            <span class="glyphicon glyphicon-user"></span>
            <h4>Students</h4>
            <p>{{ total_students }} </p>
          </div>
        </div>
        <a href="{% url 'classroom:teacher_subjects' %}">
        <div class="col-sm-3">
          <div class="well" id="subjects">
             <span class="glyphicon glyphicon-book "></span>
            <h4>Subjects</h4>
            <p>{{ total_subjects }} </p>
          </div>
        </div>
         </a>
          <a href="{% url 'classroom:attendance_days' %}">
        <div class="col-sm-3">
          <div class="well" id="attendance">
              <span class="glyphicon glyphicon-edit"></span>
            <h4>Attendance</h4>
              <p> {{ total_days }} days</p>
          </div>
        </div>
         </a>
        <div class="col-sm-3">
          <div class="well" id="graphs">
              <span class="glyphicon glyphicon-equalizer"></span>
            <h4>Performance graphs</h4>
            <p>30%</p>
          </div>
        </div>
      </div>
     <div class="row">
    <div class="col-md-4">
        <img src="{% static 'img/girl2.png' %}" class="rounded" alt="profile_picture" width="200" height="200" >
      <table class="table table-striped">
          <thead>
          <tr>
              <td></td>
              <td></td>
          </tr>
          </thead>
          <tbody>
          <tr>
              <td><b>First Name</b></td>
              <td>{{ teacher.first_name }}</td>
          </tr>
          <tr>
              <td><b>Last Name</b></td>
              <td>{{ teacher.last_name }}</td>
          </tr>
          <tr>
              <td><b>Phone Number</b></td>
              <td>{{ teacher.phone_number }}</td>
          </tr>
          <tr>
              <td><b>Email</b></td>
              <td>{{ teacher.email }}</td>
          </tr>
          </tbody>
      </table>
    </div>
         <div class="col-md-8 ">
             <br>
             <br>
             <br>
             <br>
          <table class="table table-striped table-bordered" id="studentList" style="width:100%">
              <thead>
               <tr><td>First Name</td><td>Middle Name</td><td>Last Name</td><td>Email</td><td></td></tr>
              </thead>
              <tbody>
                 {% for student in students %}
                  <tr>
                      <td>{{ student.first_name }}</td>
                      <td>{{ student.second_name }}</td>
                      <td>{{ student.last_name }}</td>
                      <td>{{ student.email }}</td>
                    <td><a href="{% url 'students:student_detail' pk=student.pk %}" ><button type="submit" name="student_pk" value="{{ student.pk }}" class="btn btn-primary">View</button></a></td>
                  </tr>
                 {% endfor %}

              </tbody>
          <tfoot></tfoot>
          </table>
         </div>
  </div>
      </div>
    </div>
</div>
<script>
   $(document).ready( function () {
    $('#studentList').DataTable();
} );
</script>


</body>
</html>

StudentsPerformanceAnalysis3/templates/classroom/teachers/teacher_subjects_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <table class="table table-striped table-bordered" id="studentList" style="width:100%">
              <thead>
              <tr><td><b>Subject</b></td><td><b>Tests</b></td><td></td></tr>
              </thead>
              <tbody>
                 {% for subject in subjects %}
                  <tr>
                      <td>{{ subject.subject_title }}</td>
                      <td>{{ subject.number_of_tests }}</td>
                      <td><a href="{% url 'classroom:subject_tests' pk=subject.pk %}"><button class="btn btn-block btn-primary" ><b>View</b></button></a></td>
                   </tr>
                 {% endfor %}

              </tbody>
          <tfoot></tfoot>
          </table>
{% endblock %}

StudentsPerformanceAnalysis3/templates/classroom/teachers/teacher_update_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}